apiVersion: v1
kind: Service
metadata:
  name: community-solid-server
  annotations:
    # MetalLB annotations for load balancer configuration
    metallb.universe.tf/allow-shared-ip: "css-shared"
    metallb.universe.tf/loadBalancerIPs: "10.0.0.1"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.1  # Fixed IP for MetalLB
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
