apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-solid-server
spec:
  template:
    spec:
      containers:
        - name: community-solid-server
          args:
            - "-l"
            - "info"
            - "-b"
            - "http://community-solid-server.solid/"
            - "-c"
            - "config/default.json"
            - "-f"
            - "/data/"
            - "-w"
            - "-1"  # Use num_cores-1 workers (can be overridden)
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
