---
# Source: community-solid-server/templates/persistentVolumeClaim.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: community-solid-server-data
  labels:
    app.kubernetes.io/name: community-solid-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
