apiVersion: v1
kind: Service
metadata:
  name: community-solid-server
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30080  # Fixed NodePort (can be overridden)
