---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Local development in my shop is on Proxmox with MetalLB.

metadata:
  name: css-local-proxmox

resources:
  - ../../base

components:
  - ../../components/pvc
  - ../../components/metallb-loadbalancer
  - ../../components/sparql-endpoint
  - ../../components/security-hardening
  - ../../components/env-vars

images:
  - name: docker.io/solidproject/community-server
    newTag: 6.0.2

labels:
  - pairs:
      app.kubernetes.io/instance: css-local-proxmox
      app.kubernetes.io/version: "0.3.0"

patches:
  - path: metallb-ip-patch.yaml
    target:
      kind: Service
      name: community-solid-server
  - target:
      kind: Service
      name: community-solid-server
    patch: |-
      - op: replace
        path: /spec/selector/app.kubernetes.io~1instance
        value: css-local-proxmox
  - target:
      kind: Deployment
      name: community-solid-server
    patch: |-
      - op: replace
        path: /spec/selector/matchLabels/app.kubernetes.io~1instance
        value: css-local-proxmox
      - op: replace
        path: /spec/template/metadata/labels/app.kubernetes.io~1instance
        value: css-local-proxmox

namespace: solid
