apiVersion: v1
kind: Service
metadata:
  name: community-solid-server
  annotations:
    # Override MetalLB IP configuration for local-proxmox environment
    metallb.universe.tf/loadBalancerIPs: "192.168.1.81"
spec:
  loadBalancerIP: 192.168.1.81  # Override IP for local-proxmox environment
