apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: css-high-performance

resources:
  - ../../base

components:
  - ../../components/pvc
  - ../../components/multithreading
  - ../../components/custom-config
  - ../../components/env-vars
  - ../../components/security-hardening

images:
  - name: docker.io/solidproject/community-server
    newTag: 6.0.2

labels:
  - pairs:
      app.kubernetes.io/instance: css-high-performance
      app.kubernetes.io/version: "0.3.0"

patches:
  - path: performance-patch.yaml
  - target:
      kind: Service
      name: community-solid-server
    patch: |-
      - op: replace
        path: /spec/selector/app.kubernetes.io~1instance
        value: css-high-performance
  - target:
      kind: Deployment
      name: community-solid-server
    patch: |-
      - op: replace
        path: /spec/selector/matchLabels/app.kubernetes.io~1instance
        value: css-high-performance
      - op: replace
        path: /spec/template/metadata/labels/app.kubernetes.io~1instance
        value: css-high-performance

namespace: solid
