apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: css-with-ingress-sparql

namespace: solid

resources:
  - ../../base

components:
  - ../../components/pvc
  - ../../components/ingress
  - ../../components/sparql-endpoint
  - ../../components/env-vars

images:
  - name: docker.io/solidproject/community-server
    newTag: 6.0.2

labels:
  - pairs:
      app.kubernetes.io/instance: css-with-ingress-sparql
      app.kubernetes.io/version: "0.3.0"

patches:
  - path: ingress-patch.yaml
  - target:
      kind: Service
      name: community-solid-server
    patch: |-
      - op: replace
        path: /spec/selector/app.kubernetes.io~1instance
        value: css-with-ingress-sparql
  - target:
      kind: Deployment
      name: community-solid-server
    patch: |-
      - op: replace
        path: /spec/selector/matchLabels/app.kubernetes.io~1instance
        value: css-with-ingress-sparql
      - op: replace
        path: /spec/template/metadata/labels/app.kubernetes.io~1instance
        value: css-with-ingress-sparql
