---
# Source: community-solid-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-solid-server
  labels:
    app.kubernetes.io/name: community-solid-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: community-solid-server
      app.kubernetes.io/instance: base
  template:
    metadata:
      labels:
        app.kubernetes.io/name: community-solid-server
        app.kubernetes.io/instance: base
    spec:
      enableServiceLinks: false
      containers:
        - name: community-solid-server
          image: "docker.io/solidproject/community-server:6.0.2"
          args:
            - "-l"
            - "info"
            - "-b"
            - "http://community-solid-server.solid/"
            - "-c"
            - "config/default.json"
            - "-f"
            - "/data/"
          env: []
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
        - name: data
          emptyDir: {}
