---
apiVersion: v1
kind: Service
metadata:
  name: community-solid-server
  labels:
    app.kubernetes.io/name: community-solid-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: community-solid-server
    app.kubernetes.io/instance: base
